# Generated by Django 4.2.7 on 2023-11-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('member_type', models.CharField(choices=[('0', 'NEWBIE'), ('1', 'ANIME LOVER'), ('2', 'WEEBO'), ('3', 'UNDEFEATED WEEBO')], default=('0', 'NEWBIE'), max_length=30)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
