# Generated by Django 4.2.7 on 2023-11-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userpersonal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
