# Generated by Django 5.0 on 2023-12-11 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userpersonal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
