# Generated by Django 5.0 on 2023-12-11 09:56

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=255, unique=True)),
                ('catagory_image', models.FileField(blank=True, null=True, upload_to='catagories/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, default=0, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('product_catagory', models.ForeignKey(default=products.models.Catagory.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='products.catagory')),
            ],
        ),
    ]
