# Generated by Django 4.2.7 on 2023-11-24 21:53

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_discount_proce_product_discount_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_catagory',
            field=models.ForeignKey(default=products.models.Catagory.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='products.catagory'),
        ),
    ]
